
generate_tree <- function(ntaxa, replics) {
  
  require(phangorn) #mandatory library
  require(phytools) #mandatory library
  
  
for (i in 1:replics){

  set.seed(1234*i) #set the seed for replications
  
  #####################
  ## generate trees ##
  #####################

  tree <- rtree(ntaxa, rooted = T, br = 1) #branch lengths equals to 1 for all
  
  tree_exp <- tree #same topology but different name
  tree_exp$edge.length <- rexp(n = tree_exp$Nnode + ntaxa - 1, rate = 1) #assign branch length under exponential distribution
  

#####################
## generate matrix ##
#####################

#matriz.char.irreversible <- rTraitDisc(tree, states = c(0,1), model = matrix(c(0, 0, 0.1, 0), 2)) #irreversible matrix parameters

  matriz.char.mk2 <- rTraitDisc(tree, states = c(0,1)) #simulate matriz under MK model, 
  matriz.char.mk2.expo <- rTraitDisc(tree_exp, states = c(0,1)) #simulate matriz under MK model for exponential br.length
  
  matriz.char.homoplasy <- sample(x = c(0,1), size = ntaxa, prob = c(0.5,0.5), replace = T) #homoplasy matrix parameters
  names(matriz.char.homoplasy) <- names(matriz.char.mk2) #assign names to matrix

  matriz.char.homoplasy.expo <- matriz.char.homoplasy
 
############################################
## write matrix in nexus and tree in nexus##
############################################

#write.nexus.data(as.matrix(matriz.char.irreversible), file = paste("/home/andresfoc/Desktop/MEGA/9sem/comparadaII/Proyecto/resultados/", "matriz_irreversible_", "rep", i, "_ntaxa", ntaxa, ".nex", sep = ""), format = "standard")

  write.nexus.data(as.matrix(matriz.char.homoplasy), file = paste("./results/", "matriz__", "rep", i, "_homoplasy", "_ntaxa", ntaxa, ".nex", sep = ""), format = "Standard") #write matrix under uniform generation and with br.length equal to 1

  write.nexus.data(as.matrix(matriz.char.homoplasy.expo), file = paste("./results/", "matriz_expo_rep", i, "_homoplasy", "_ntaxa", ntaxa, ".nex", sep = ""), format = "Standard") #write matrix under uniform generation and with br.length under exponential distribution


  write.nexus.data(as.matrix(matriz.char.mk2), file = paste("./results/", "matriz__", "rep", i, "_mk2_ntaxa", ntaxa, ".nex", sep = ""), format = "standard") #write matrix under Mk2 generation and with br.length equal to 1
  
  write.nexus.data(as.matrix(matriz.char.mk2.expo), file = paste("./results/", "matriz_expo_rep", i, "_mk2_", "_ntaxa", ntaxa, ".nex", sep = ""), format = "standard") #write matrix under Mk2 generation and with br.length under exponential distribution


  writeNexus(tree = tree, file = paste("./results/", "tree_", "rep", i, "_ntaxa", ntaxa, ".nex", sep = "")) #write the tree with br.lengths equal to 1
  
  writeNexus(tree = tree_exp, file = paste("./results/", "tree_expo_", "rep", i, "_ntaxa", ntaxa, ".nex", sep = "")) #write the tree with br.lengths generated by exponential model
}
}

###

for (i in c(10, 40, 160)){
generate_tree(i, replics = 3)
}
